### ISSUE TITLE
Using Micro without SideCar in Ruby

### ISSUE THREAD

**Issue by alexsotocx** [micro/micro#121]
Hello,

I just want to know if there is a way of using the full framework in Ruby without using Sidecar. I was interested because there is Ja-micro created by Sixt and is the Java framework Compatible with Micro.

Is there anything similar in Ruby or is there any documentation of what the framework(a new one in ruby) needs to implement to be Compatible with Micro.

Thanks for the great work.

**Comment by asim** [comment]
There is currently nothing in ruby beyond frameworks that leverage the sidecar such as [micro-rb](https://github.com/amedeiros/micro-rb). Building a full framework in any language would be quite an extensive task. 

There's no documentation to indicate what a compatible framework should be like. Sixt chose to write something which was compatible but which catered to their specific java development needs. 

There are a few bare minimum requirements to be compatible with the default plugins but note plugins can be swapped out so maintaining parity with every plugin would be a difficult task.

1. Transport - the transport uses http request/response over a tcp connection. It supports streaming of requests or responses back and forth in the form of a bidirectional stream of http 1.1. Requests are made as a POST request. Find the transport here https://github.com/micro/go-micro/blob/master/transport/http_transport.go

2. Encoding - Messages sent over the transport are encoded in either protobuf or json. The envelope for a proto message is here https://github.com/micro/go-micro/blob/master/codec/protorpc/envelope.proto. With protobuf we write the length of the message then the message itself, see the code here https://github.com/micro/go-micro/blob/master/codec/protorpc/netstring.go. JSON request/response is json-rpc 1.0. You can find the request/response here https://github.com/micro/go-micro/blob/master/codec/jsonrpc/client.go. The specification can be found here http://json-rpc.org/wiki/specification.

3. Registry - Services find each other using service discovery. The default implementation is using consul. The consul discovery code in itself is quite complex since consul only supports string tags for metadata and we need to store more than that. You can find the implementation here https://github.com/micro/go-micro/blob/master/registry/consul_registry.go.

A note about all this. It's become clear over the past couple years that replicating go-micro is extremely difficult. It would be a full time job. We should instead leverage go-micro and improve the sidecar so that apps written in any language can benefit from it. 

Some ideas

1. The sidecar should automatically register the app on start and health check it to ensure its alive, deregistering if there's an issue. 
2. Service discovery should be transparent to the app. /foo/bar going to the foo service.
3. Users should be able to leverage http and send json or protobuf as the body of the request.
4. The broker/event bus should also be available in a /event endpoint or something similar for messaging.

If you see some pain points with the sidecar, please let me know so we can address them.

**Comment by alexsotocx** [comment]
Sure, Thanks for the information. I find this project so interesting over the pass weeks so maybe I will try to create it in my free time.  

I will look in deep into sidecar to see how it works and if I can make it work with my ideas. At the moment are just ideas.
