### ISSUE TITLE
go-micro v2 maintenance

### ISSUE THREAD

**Issue by marlonfan** [micro/micro#1651]
I really like this project. But the new version bothered me a little. Will the go-micro v2 release be maintained and updated?

**Comment by asim** [comment]
Go Micro v2 is currently on hold and not maintained by anyone. Its still accepting PRs and contributions.

**Comment by marlonfan** [comment]
Can I switch a branch to continue maintenance?

**Comment by alihalabyah** [comment]
@asim I would like to say thank you for the great work!, however, now since micro is getting growing attention from the community I would say not maintaining v2 suddenly won't be very pleasant especially that the difference between v2 and v3 is big and people like us are still trying to get familiar and/or struggling with not ready or opaque issues such as https://github.com/micro/micro/issues/1628

Can we try to see if the contributors of v2 are still interested in maintaining it? and Have you tried to look for incubation as this kind of projects can grow longer easily? :)

**Comment by asim** [comment]
My experience with V2 is the majority were using go-micro and potentially the micro API. Unfortunately after 6 years of maintaining a free v1-v2, the majority of which I did alone it's not something I find myself wanting to continue on with. The company is focused on the development of a platform and related services. That effort now eclipses any sort of open source requirements. V3 is a large refactor addressing a lot of the issues with v1-v2 and the complexity of that tooling. Unfortunately I can't ask my team to maintain a legacy artifact that was built by myself. In v3 we're taking a very consolidated approach that's more true to my original vision.

If you'd like to maintain V2 then please feel free to fork and establish a new community based on that effort as others are trying. Otherwise I cannot unfortunately provide any support there considering its entirely free software for which I received no help or support from the community with.

**Comment by abogushov** [comment]
@asim Thanks for your work, I really like the design of the Micro v3! We understand that PaaS is your goal and your team works hard on it. But many of us try to adopt v3 for our projects and it's quite hard right now because documentation is not complete (it is OK, we can read the sources), and they're also a potential risk that only PaaS will be fully functional and supported by the Micro team. Many questions arise about v3 (#1514 #1661 #1624 #1628). I try to decide is it worth time to spend on Micro v3 or I need to switch on v2 or maybe develop microservices without any framework. Could you, please, provide your vision of the Micro v3 future?

**Comment by asim** [comment]
Micro v3 is an operating system for the Cloud. Think Android for Cloud. Currently the cloud is too complex and we spent a significant amount of time trying to manage operations where we should really be focusing on the service development and consumption. Micro v3 is an attempt in standardisation around that, the development model, the consumption model and the operating model. You can find extensive v3 docs on the website, https://micro.mu. We have also specified an upgrade guide from v2. In any case, this is a major departure from what we were doing in a hugely fragmented model that evolved over 5-6 years. Go Micro is now no longer managed by the company or entity known as Micro. We've consolidated the framework in as it was always part of a broader set of tools for a platform.

Micro no longer attempts to cater to a self hosted open source audience. We are in fact building micro for ourselves to power a cloud platform. If it happens to be of use to you, that's great, but we otherwise are not expecting anyone to pick up and run this anymore.
