### ISSUE TITLE
Failed to connect to micro server at 127.0.0.1:8081

### ISSUE THREAD

**Issue by navysummer** [micro/micro#1771]
go get github.com/micro/micro/v3

micro env set local

micro server

micro new helloworld

micro run helloworld

Error creating stream: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused"

**Comment by AstarLight** [comment]
firstly, you should use these command:

micro server 
micro login


account:admin
password:micro

**Comment by DKLuck** [comment]
$ micro login
Enter username: admin
Enter password:
Connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8081: connectex: No connection could be made because the target machine actively refused it."


run for windows10

My host:
# localhost name resolution is handled within DNS itself.
#127.0.0.1 localhost
#localhost 127.0.0.1
#::1 localhost



# Added by Docker Desktop
192.168.17.177 host.docker.internal
192.168.17.177 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

**Comment by DKLuck** [comment]
$ micro service
2021-07-17 13:10:21  file=service/service.go:118 level=info Service [mucp] Serving service at endpoint localhost:9090

2021-07-17 13:10:21  file=service/service.go:195 level=info Starting [service] service
2021-07-17 13:10:21  file=grpc/grpc.go:938 level=info Server [grpc] Listening on [::]:58850
2021-07-17 13:10:21  file=grpc/grpc.go:768 level=info Registry [service] Registering node: service-815eac4c-5199-4910-8a01-dd1e8f76b1b6
2021-07-17 13:10:30  file=grpc/grpc.go:962 level=error Server register error: {"Id":"go.micro.client","Code":500,"Detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connectex: No connection could
be made because the target machine actively refused it.\"","Status":"Internal Server Error"}

**Comment by DKLuck** [comment]
All Security software shut down

**Comment by nelsonkti** [comment]
micro env set local

micro signup

micro server

micro server

micro login

**Comment by sunny-sjj** [comment]
> 2021-07-17 13:10:21 file=service/service.go:195 level=info Starting [service] service 2021-07-17 13:10:21 file=grpc/grpc.go:938 level=info Server [grpc] Listening on [::]:58850 2021-07-17 13:10:21 file=grpc/grpc.go:768 level=info Registry [service] Registering node: service-815eac4c-5199-4910-8a01-dd1e8f76b1b6 2021-07-17 13:10:30 file=grpc/grpc.go:962 level=error Server register error: {"Id":"go.micro.client","Code":500,"Detail":"connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8081: connectex: No connection could be made because the target machine actively refused it."","Status":"Internal Server Error"}

hi, have you solved this problem?

**Comment by Dart-Sharma** [comment]
{"id":"ea4c1001-f0df-47e8-b7b5-6ba7632788fa","createdAt":"2023-11-07T07:01:07.287Z","runtimeVersion":"exposdk:49.0.0","launchAsset":{"key":"bundle","contentType":"application/javascript","url":"http://127.0.0.1:8081/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&lazy=true"},"assets":[],"metadata":{},"extra":{"eas":{},"expoClient":{"name":"Axon-Mobile","slug":"Axon-Mobile","version":"1.0.0","orientation":"portrait","icon":"./assets/icon.png","userInterfaceStyle":"light","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"http://127.0.0.1:8081/assets/./assets/splash.png"},"assetBundlePatterns":["**/*"],"ios":{"supportsTablet":true},"android":{"permissions":["NAVIGATION"],"adaptiveIcon":{"foregroundImage":"./assets/adaptive-icon.png","backgroundColor":"#ffffff","foregroundImageUrl":"http://127.0.0.1:8081/assets/./assets/adaptive-icon.png"}},"web":{"favicon":"./assets/favicon.png"},"_internal":{"isDebug":false,"projectRoot":"E:\\react native\\Git\\Axon-Mobile","dynamicConfigPath":null,"staticConfigPath":"E:\\react native\\Git\\Axon-Mobile\\app.json","packageJsonPath":"E:\\react native\\Git\\Axon-Mobile\\package.json"},"sdkVersion":"49.0.0","platforms":["ios","android"],"iconUrl":"http://127.0.0.1:8081/assets/./assets/icon.png","hostUri":"127.0.0.1:8081"},"expoGo":{"debuggerHost":"127.0.0.1:8081","logUrl":"http://127.0.0.1:8081/logs","developer":{"tool":"expo-cli","projectRoot":"E:\\react native\\Git\\Axon-Mobile"},"packagerOpts":{"dev":true},"mainModuleName":"node_modules\\expo\\AppEntry","__flipperHack":"React Native packager is running"},"scopeKey":"@anonymous/Axon-Mobile-aa822339-b7e1-469a-b671-1b427a350d18"}}
