### ISSUE TITLE
Unclear how to call `service.New()` and pass cli flags as options

### ISSUE THREAD

**Issue by dsuare1** [micro/micro#1870]
Hello!

First off, my apologies if this is not the correct place to post this; I've searched and searched for proper documentation, a Slack channel, or any type of support forum, but to no avail. If one of those exists, please kindly point me in that direction :)

I've inherited a project from 2018 using micro (using the old `github.com/micro/go-micro`, and I'm working to update it. I'm currently importing `github.com/micro/micro/v3/service`, which gives me access to the API `service.New(...)`.

One of the options being supplied previously was `micro.Flags(flags []github.com/micro/cli.Flag)`; sample code:

```
grpcService := service.New(
	service.Name(config.ServiceName),
	service.Version("latest"),
	service.RegisterTTL(time.Second*30),
	service.RegisterInterval(time.Second*10),
	service.Flags(cliFlags...),                                             <--- the missing API in question
	service.Action(func(c *cli.Context) {
		config.InitWithCLIContext(c)
	}),
)
```

However, in the `/v3/service` API, this option seems to have been removed.

Again, my apologies if this is not the correct means by which to ask this. Any help / guidance is appreciated.

**Comment by h1z3y3** [comment]
`go-micro` is moved to `https://github.com/asim/go-micro`, 
I think you should import `https://github.com/asim/go-micro` rather than `github.com/micro/micro/v3/service`.

They are different projects, and not compatible with each other.

For more information: https://micro.mu/faq#whats-the-difference-between-micro-and-go-micro

Hope it helps. :)
