### ISSUE TITLE
No private IP address found, and explicit IP not provided

### ISSUE THREAD

**Issue by prettyyjnic** [micro/micro#206]
when i run 
`
go get github.com/micro/examples/greeter/srv && srv
`
I got error
`
2018/10/25 19:50:39 Listening on [::]:35820
2018/10/25 19:50:39 Broker Listening on [::]:44523
2018/10/25 19:50:39 No private IP address found, and explicit IP not provid
`

**Comment by asim** [comment]
Heres the function which extracts the address https://github.com/micro/util/blob/master/go/lib/addr/addr.go#L31

See at top of file the IP address blocks supported for binding to. We expect there to be a private address available to automatically bind otherwise you must specify one yourself with the server address flag or env var.
