### ISSUE TITLE
Concept hitting GRPC directly...

### ISSUE THREAD

**Issue by pawmart** [micro/micro#220]
Hi there,

I have a question regarding GRPC...

1. I have micro api (RPC handler) on. (I can do http requests via api with no problems)
2. My proto generated 'clients' correctly and I am able to define a call...
3. But which endpoint should I hit, where this the host for rpc direct calls?

Example in PHP:

```
$messanger = new Namespace\MessengerClient('http://localhost::8080/rpc', ['credentials' => Grpc\ChannelCredentials::createInsecure()]);
list($response, $status) = $messanger->SendSms($sendSmsRequest)->wait();

var_dump($response);
var_dump($response->getStatus());
var_dump($status);
```

My question is about the 'host' I should be hitting... to go directly rpc instead of http...

Hope my question makes sense....

**Comment by asim** [comment]
The micro api does not support direct grpc calls. The /rpc endpoint expects you to specify service, method, etc as part of the request. The micro api builds on the go-api which has a set of handlers here https://github.com/micro/go-api/tree/master/handler. You can add support for grpc if you have time. 

You can otherwise setup the micro api with the grpc client plugin and use the grpc resolver with --resolver=grpc which should allow you to send grpc requests directly and it will do the service discovery for you.

**Comment by pawmart** [comment]
OK, perfect, thank you for your info @asim !
