### ISSUE TITLE
Plans for adding back /registry handler in proxy or similar?

### ISSUE THREAD

**Issue by matchbookmac** [micro/micro#294]
Thanks for all your work on micro. We've been using for a long time and it's helped us a lot.

Looks like recent updates to the `micro proxy` command have made it such that you can no longer register services over HTTP through the proxy. Is there a new way to do this, or has this feature been removed? Most of our services are not written in go, so not being able to register a service through a sidecar or the like over HTTP has us hamstrung.

Any help would be much appreciated, thanks.

**Comment by asim** [comment]
There's a couple different approaches you can take for this. We've essentially looked to deprecate that feature as it's not really how we see the usage moving forward. 

One way is to run the micro API with the registry handler setting --handler=registry. This provides the registry as a http API.

Another approach is to use the cli to register using the command "micro register" service. 

A third approach we're looking at is service encapsulation via a "micro service" command. This is available but if you're using http apps it would require using the http server plugin. We'll provide further explanation of this once it's fleshed out more. 

Otherwise you can always write a tiny go script that uses the go library to register the service.

**Comment by matchbookmac** [comment]
Gotcha, thanks for the explanation @asim! Will try some of these options out. Cheers and thanks for the free tools!
