### ISSUE TITLE
Include plugins

### ISSUE THREAD

**Issue by phifty** [micro/micro#47]
It would be nice if the plugin repository is included in the build. I would like to connect to a `nats` registry using the `micro` command. It would also be useful if I could pass a `secure` option to registry, transport and broker.

**Comment by asim** [comment]
Plugins in go-plugins will not be included in the build. They were removed early on because of bloat and potential frequent breaks because of all the different dependencies that were outside our control. Certain specific things will live in go-micro such as consul and mdns for registry,  http and mqtt for broker, etc, etc. 

We may provide tagged builds of docker images in the future, releases that prepackage plugins or separate branches but there's no immediate plan to include what's in go-plugins into the main repos.

**Comment by asim** [comment]
If you would like to pass extra opts into the various packages, initialise them separately and then pass them in for use to a new service. Alternatively call service.Server().Options().{Broker, Registry, Transport}.Init with your params. More syntactic sugar for top level opts may be added later.

**Comment by phifty** [comment]
Ok thanks for the quick reply!
