### ISSUE TITLE
Websocket for streams?

### ISSUE THREAD

**Issue by filipninja** [micro/micro#66]
Are there any plans to develop websocket facade for streams similar to api gateway for rpc?

So it could allow to expose via websocket
`rpc PingPong(stream Ping) returns (stream Pong) {}`

I would be happy to contribute, if we could agree on requirements... 

Or you have better ideas how to stream data bidirectionally between browser and go-micro services, brokers, subscribers?

**Comment by asim** [comment]
There's no current plans to add websockets or streaming support to the API. The micro web proxy provides support for web sockets which can be useful for anyone who needs that support. On the API side I opted simply for standard http requests which can easily be converted to an RPC format or a reverse proxy is built in otherwise for those who want to deal with the http request.  While stream support would be useful, it's not a simple feature and I haven't yet thought of an elegant way for it to be used.
