### ISSUE TITLE
"micro api" getting error "...accept4: too many open files..." after usage for a while

### ISSUE THREAD

**Issue by TomOgoma** [micro/micro#85]
## Issue

After running `micro api` for some time all new requests to the api stop being served.
The logs yield the following message:

```
2017/01/13 19:05:19 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 1s
```

## SetUp

I'm running `micro api` command as a `systemctl` service on an Ubuntu 16.04 server with 1GB RAM and 2GB swap space ...together with `consul consul agent -dev -advertise=127.0.0.1` (also as a systemctl service) with 4 microservices (no redundancy) behind the setup.

This is the first time I'm experiencing the issue after running the setup for nearly a month. Restarting the 'service' seems to solve the problem.

**Comment by asim** [comment]
Have you googled the error? This is a golang http server error which is mainly related to the open file limit https://github.com/golang/go/issues/3167

What is your open file limit? How often is this error appearing? How is this API being used? What type of request is being made? By which type of client? What are the API services behind this?

**Comment by asim** [comment]
Please respond to the issue or it will be closed. Thanks.

**Comment by TomOgoma** [comment]
> What is your open file limit?

 1024 at the time of posting, I've since increased the value to 50000

> How often is the error appearing?

 It occured twice since we started using the API - been using it for around 2 months now.

> How is the API being used; what are the API services behind this?

We are using it as a http gateway to 4 or more golang microservices which use the go-micro library for serving RPC requests.

The API is run as a systemctl service which runs the command `micro api`

Consul is also run as a systemctl service using the command `consul consul agent -dev -advertise=127.0.0.1`

>What type of request is being made?

Clients communicate by make RPC calls via the /rpc endpoint of the listening port (8080) with content-type set to json as in https://github.com/micro/micro/tree/master/api examples

> By which type of client (the requests)?

Currently the clients are android devices configured to periodically sync data with two types of requests: normal CRUD operations and periodic pings (frequency of 1 ping randomly run within a 24 hour interval per device).

> Have you googled this?

I  chose to raise this based on a comment mentioning that this could be because the program is closing something that shouldn't be closed? Maybe raising the open file limit will help? My apologies if raising an issue was not the right thing to do.

**Comment by asim** [comment]
Thanks for the detailed response. As soon as I hear the words "android devices" it all starts to make more sense. From what I recall java based http clients are known to keep connections open. If you have many of these clients performing both crud and ping operations then this could firstly result in a number of requests obviously and secondly result in a number of connections kept open which inevitably leads to the open file limit being hit and the server complaining about not being able to create a new connection.

Increasing the open file limit will help reduce the frequency of the problem you're facing but may not be a permanent fix. Since this is the first time I'm hearing about the issue in regard to the micro api I'm going to avoid any code changes on my side. Please go with the open file limit fix and report back if there are any further issues. I'm going to close this issue but please reopen if you see the issue again. In which case we'll likely make a code change to set read/write timeouts on the server.

**Comment by TomOgoma** [comment]
Thanks @asim . I'll monitor and report back if the issue comes up again.

**Comment by lpeano** [comment]
You ave to increase somaxconn from 128 to 1000.
This extend tcp backlog queue to the listener
