### ISSUE TITLE
'malformed method name' in new service

### ISSUE THREAD

**Issue by vishvish** [micro/micro#936]
Creating a new service with `micro new` and then immediately running it with `micro run ./` results in multiple errors being logged. Service example is called `reporeader`:

`2020-06-10 11:10:37  file=handler/handler.go:227 level=error service=debug Error calling default/go.micro.service.reporeader@192.168.1.159:56378 ({"id":"go.micro.client","code":500,"detail":"malformed method name: \"/default/go.micro.service.reporeader.Debug/Trace\"","status":"Internal Server Error"})`

Steps to replicate:

`micro new reporeader`
`cd reporeader`
`go get -u github.com/golang/protobuf/proto`
`go get -u github.com/golang/protobuf/protoc-gen-go`
`go get github.com/micro/micro/v2/cmd/protoc-gen-micro@master`

`protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. proto/reporeader/reporeader.proto`

`micro run ./`

**Comment by asim** [comment]
As per discussion in #platform we feel the problem is the following

1. services run by the runtime with micro run are being registered by the registry service with a default/ prefix
2. the debug service is pulling a service list directly from the registry interface rather than the registry service and its getting service names with this prefix rather than it being stripped

Possible solutions

1. The debug service calls the registry service rather than using the registry interface
2. The code used to prefix/remove namespace is a shared library 
3. The namespace is not prefixed to service names but is instead an optional domain field

**Comment by vishvish** [comment]
I have removed every aspect of micro and reinstalled from scratch, and created a new service with `micro new --namespace` and things seem to working more correctly, might be an interface or contract incompatibiilty between versions within micro somewhere?

**Comment by asim** [comment]
Yes there may be versioning issues. v1 is not compatible with v2 and there are some bugs in certain releases in v2 so hopefully using latest release helps
