### ISSUE TITLE
API not handles json post data

### ISSUE THREAD

**Issue by vyacheslavk** [micro/micro#98]
Does anyone have an issue getting request information from api?
I have proto request
```proto
message Request {
    string email = 1;
    string password = 2;
}
```
and service go.micro.api.secure
```proto
service Secure {
    rpc Login (Request) returns (Response) {
    };
}
```
so when i start 
```bash 
micro api
```
everything is ok, but when i send request for example ` http --json POST http://localhost:8080/secure/login  email=test@test.com password="testPassword"`

```golang
func (s *Secure) Login(ctx context.Context, req *apiAuth.Request, rsp *apiAuth.Response) error {
	log.Printf("%s: Authorization for email %s & password %s ", s.Client.String(), req.Email, req.Password)
}
```
I get `rpc: Authorization for email POST & password /secure/login` not email and password.

**Comment by asim** [comment]
Are you running the api with the rpc handler? Because it's not going to parse the body of the request and pass through what you expect unless you do that by setting `--handler=rpc`. The default handler is the api handler which expects the api.Request/Response types found here https://github.com/micro/go-api/tree/master/proto

**Comment by vyacheslavk** [comment]
Right, I forgot to put `--handler=rpc` on start.
Thanks!
